# Site Information
site_name: Text-to-Speech for Discord
site_description: Documentation site for moonstar-x/discord-tts-bot.
site_author: moonstar-x
site_url: https://docs.moonstar-x.dev/discord-tts-bot/

# Repo
repo_name: moonstar-x/discord-tts-bot
repo_url: https://github.com/moonstar-x/discord-tts-bot
edit_uri: ''

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moonstar-x
      name: moonstar-x's GitHub Profile
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moonstar_x99
      name: moonstar-x on Twitter
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mhj3Zsv
      name: moonstar-x's Discord Server
    - icon: fontawesome/solid/globe-americas
      link: https://moonstar-x.dev
      name: moonstar-x's Website
    - icon: fontawesome/solid/coffee
      link: https://ko-fi.com/moonstar_x
      name: Buy moonstar-x a coffee
  analytics:
    provider: google
    property: G-TBGX3DR6K2

# Copyright
copyright: Copyright &copy; 2022 moonstar-x

# Theme Customization
theme:
  name: material
  palette:
    - scheme: default
      primary: light blue
      accent: indigo
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: indigo
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/git-alt
  language: en
  direction: ltr
  favicon: assets/logo.png
  logo: assets/logo.png
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.highlight

# Extensions
markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

# Navigation
nav:
  - Home: index.md
  - Installation:
    - Introduction: installation/index.md
    - Setting Up: installation/setting-up.md
    - Node (Normal): installation/node-normal.md
    - Docker: installation/docker.md
    - Repl.it: installation/replit.md
    - Heroku: installation/heroku.md
  - Updating:
    - Introduction: updating/index.md
    - Node (Normal): updating/node-normal.md
    - Docker: updating/docker.md
    - Repl.it: updating/replit.md
    - Heroku: updating/heroku.md
  - Commands:
    - Introduction: commands/index.md
    - All TTS Commands:
      - /say: commands/all-tts/say.md
      - /stop: commands/all-tts/stop.md
    - Google TTS Commands:
      - /google_say: commands/google-tts/google-say.md
      - /google_langs: commands/google-tts/google-langs.md
      - /google_set_default: commands/google-tts/google-set-default.md
      - /google_set_my: commands/google-tts/google-set-my.md
    - Amazon (TTS Tool) TTS Commands:
      - /amazon_say: commands/amazon-tts/amazon-say.md
      - /amazon_langs: commands/amazon-tts/amazon-langs.md
      - /amazon_voices: commands/amazon-tts/amazon-voices.md
      - /amazon_set_default: commands/amazon-tts/amazon-set-default.md
      - /amazon_set_my: commands/amazon-tts/amazon-set-my.md
    - Microsoft (TTS Tool) TTS Commands:
      - /ms_say: commands/ms-tts/ms-say.md
      - /ms_langs: commands/ms-tts/ms-langs.md
      - /ms_voices: commands/ms-tts/ms-voices.md
      - /ms_set_default: commands/ms-tts/ms-set-default.md
      - /ms_set_my: commands/ms-tts/ms-set-my.md
    - Other TTS Commands:
      - /aeiou_say: commands/other-tts/aeiou-say.md
    - Configuration Commands:
      - /default_settings: commands/config/default-settings.md
      - /my_settings: commands/config/my-settings.md
      - /set_default_provider: commands/config/set-default-provider.md
      - /set_my_provider: commands/config/set-my-provider.md
      - /set_locale: commands/config/set-locale.md
      - /set_timeout: commands/config/set-timeout.md
    - Miscellaneous Commands:
      - /help: commands/misc/help.md
    - Channel TTS Commands:
      - Some Information: commands/channel-tts/index.md
      - Google TTS Commands:
        - /google_set_channel: commands/channel-tts/google-tts/google-set-channel.md
      - Amazon (TTS Tool) TTS Commands:
        - /amazon_set_channel: commands/channel-tts/amazon-tts/amazon-set-channel.md
      - Microsoft (TTS Tool) TTS Commands:
        - /ms_set_channel: commands/channel-tts/ms-tts/ms-set-channel.md
      - Configuration Commands:
        - /channel_settings: commands/channel-tts/config/channel-settings.md
        - /set_channel_provider: commands/channel-tts/config/set-channel-provider.md
        - /delete_channel_provider: commands/channel-tts/config/delete-channel-provider.md
  - Text-to-Speech Providers:
    - Introduction: text-to-speech-providers/index.md
    - Google Translate Provider: text-to-speech-providers/google-translate.md
    - Amazon Provider (TTS Tool): text-to-speech-providers/amazon-ttstool.md
    - Microsoft Provider (TTS Tool): text-to-speech-providers/microsoft-ttstool.md
    - Aeiou Provider: text-to-speech-providers/aeiou.md
  - Development:
    - Introduction: development/index.md
    - Setting Up: development/setting-up.md
    - Creating a Provider: development/creating-a-provider.md
